[package]
name = "spifyrfb-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
spifyrfb-protocol = { path = "../protocol" }
tokio = { workspace = true }
windows = { workspace = true }
once_cell = { workspace = true }